version: 0.2

# AWS CodeBuild specification for React portfolio website
# This file defines the build process for the React frontend

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install
      
  pre_build:
    commands:
      - echo Running pre-build steps...
      - echo Current directory is $(pwd)
      - ls -la
      - echo Node version $(node --version)
      - echo NPM version $(npm --version)
      
  build:
    commands:
      - echo Building the React application...
      - npm run build
      - echo Build completed successfully
      
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync build/ s3://$S3_BUCKET --delete
      - echo Files uploaded to S3 bucket $S3_BUCKET
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - echo CloudFront cache invalidated for distribution $CLOUDFRONT_DISTRIBUTION_ID
      - echo Deployment completed successfully!

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
  name: portfolio-website-build

cache:
  paths:
    - frontend/node_modules/**/*